# Generated by Django 5.2.3 on 2025-11-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        # 1. BlogPostにimage2を追加
        migrations.AddField(
            model_name="blogpost",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_images/", verbose_name="画像2"
            ),
        ),
        # 2. BlogPostのimageのverbose_nameを変更
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_images/", verbose_name="画像1"
            ),
        ),
        # 3. 古いunique_togetherを削除
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        # 4. session_keyフィールドを追加
        migrations.AddField(
            model_name="like",
            name="session_key",
            field=models.CharField(
                default="", max_length=40, verbose_name="セッションキー"
            ),
            preserve_default=False,
        ),
        # 5. userフィールドを削除
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        # 6. 新しいunique_togetherを設定
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("session_key", "blog_post")},
        ),
    ]
