# Generated by Django 5.2.8 on 2025-11-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_like_unique_together_blogpost_image2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
