# Generated by Django 5.2.8 on 2025-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_comment_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="image2",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="blog_images/", verbose_name="画像"
            ),
        ),
    ]
